### ISSUE TITLE
Android build not working

### ISSUE THREAD

**Issue by jamesthomp** [Andarius/react-native-zstd#1]
Hello, thanks for creating this useful library.

The build does not seem to work for Android devices:
```
  CMake Error at CMakeLists.txt:14 (add_subdirectory):
    add_subdirectory given source "../externals/zstd/build/cmake" which is not
    an existing directory.
```

I believe this is due to including the directory here: https://github.com/Andarius/react-native-zstd/blob/main/android/CMakeLists.txt#L14
However this directory is not included in the package here: https://github.com/Andarius/react-native-zstd/blob/main/package.json#L17-L21

Let me know if this is an issue or if I've done something wrong

**Comment by Andarius** [comment]
Hey @jamesthomp, thanks for pointing out this issue and the fix. I tried to run it locally but failed to get it to work.
Can you try this branch and let me know if it works for you ? https://github.com/Andarius/react-native-zstd/tree/fix/build-android

**Comment by jamesthomp** [comment]
Thanks for getting back to me promptly. The branch you linked only has 3 commits on so I wanted to double check if that is the correct one as I would expect more commits? https://github.com/Andarius/react-native-zstd/commits/fix/build-android

What was the issue you saw when building my PR locally? I am curious how this was working for you as the code on the main branch looks to be relying on a file that is not included in the package as it is referencing `../externals/zstd/build/cmake`. I did publish my own version of the package with the changes in the PR and confirmed that it builds on mac (for iOS) & windows (for android).

If my PR isn't working then I'd be glad to try to fix it for your setup or if you prefer I can close it out as my own published version of the package is working for my needs, but I just wanted to fix this in case anyone else has the same issue!

**Comment by Andarius** [comment]
My bad, the issue I was having with your PR was because I forgot to re-run `yarn bootstrap` so we were not working with the same zstd version i guess.

You are right, I was only testing with `yarn example android` (which was working). As I was only using this library for iOS in production, I did not catch this issue.

Last question so I can understand your PR better before merging: why do you need the full zstd library (`externals/zstd/lib`) ? This library is only using the `compress`/`decompress` one.

**Comment by Andarius** [comment]
As a side note: you might run into this issue on Android (https://github.com/facebook/react-native/issues/34730). I did not have the time to investigate more, if you have a fix for that I would be happy to merge it to

**Comment by jamesthomp** [comment]
I'm not sure if the full zstd library is required. My process for modifying the package.json was:

1) See that it wasn't working and needed to reference `externals/zstd/build`, so I added that
2) It still was missing a reference to something, so figured I'd adjust to also include `externals/zstd/lib`
3) That worked, so I didn't go back to find a more minimal set of includes.

So it is possible that not everything in `externals/zstd/lib` needs to be included, but in the end this is what worked and I don't think there is too much disadvantage from including everything?

In terms of the other issue you mention - I've not experienced any issue on iOS or Android during my testing, so for whatever reason that issue doesn't seem to be a problem for me
